##############################################################################
#
# Test
#   This is the GitHub Action configuration file for testing the application
#   in this repository. This action will automatically be performed
#   whenever changes are pushed.
#
#   This .yml is based on the Github Actions YAML template for running tests:
#   https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
#
##############################################################################

# Name this Github Action.
name: Test Sklearn

# Here we can define when we want this action to happen. We currently want this
# specific action to run when changes are pushed.
on: [push]

# Here we define what jobs this action must perform.
jobs:
  build:

    # Here we determine which OS GitHub Actions should use. For convenience, we
    # run these commands on Ubuntu
    runs-on: ubuntu-latest

    # The tests are compatible with Python 3.6 - 3.10.
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    # Here we can iterate the steps that we need to take to release the latest
    # changes.
    steps:

      # First, we need to make sure that the virtual private server is updated to
      # the latest version of the repository.
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Install flake8 for linting, pytest for running tests, and any other dependencies from the requirements.txt file.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Check if the written code is up to code standards.
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Run the tests.
      - name: Test with pytest
        run: |
          pytest